=== BigDataTechOnGitHub/mongoose/scenario/schema.json
{
	"$schema" : "http://json-schema.org/draft-04/schema#",
	"definitions" : {
		"config" : {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"item": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"data": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"content": {
									"type": "object",
									"additionalProperties": false,
									"properties": {
										"file": {
											"type": [
												"null", "string"
											]
										},
										"seed": {
											"type": "string",
											"pattern" : "[A-Fa-f0-9]+"
										},
										"ringSize": {
											"oneOf" : [
												{
													"type": "integer",
													"minimum" : 1
												},
												{
													"type" : "string",
													"pattern" : "[\\d\\.]+[KMGTPE]?B?"
												}
											]
										}
									}
								},
								"ranges": {
									"type" : "object",
									"additionalProperties" : false,
									"properties" : {
										"fixed" : {
											"oneOf" : [
												{
													"type" : "null"
												},
												{
													"type" : "string",
													"pattern" : "[\\d\\.]+[KMGTPE]?B?\\-?[\\d\\.]?[KMGTPE]?B?"
												}
											]
										},
										"random" : {
											"type" : "number",
											"minimum" : 0
										},
										"threshold" : {
											"oneOf" : [
												{
													"type" : "integer",
													"minimum" : 0
												},
												{
													"type" : "string",
													"pattern" : "[\\d\\.]+[KMGTPE]?B?"
												}
											]
										}
									}
								},
								"size": {
									"oneOf" : [
										{
											"type": "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : "[\\d\\.]+[KMGTPE]?B?"
										}
									]
								},
								"verify": {
									"type": "boolean"
								}
							}
						},
						"input": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"file": {
									"type": [
										"null", "string"
									]
								},
								"path": {
									"type": [
										"null", "string"
									]
								}
							}
						},
						"naming": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"type": {
									"type": "string",
									"enum" : [
										"asc", "desc", "random"
									]
								},
								"prefix": {
									"type": [
										"null", "string"
									]
								},
								"radix": {
									"type": "integer",
									"minimum" : 2,
									"maximum" : 36
								},
								"offset": {
									"type": "integer",
									"minimum" : 0
								},
								"length": {
									"type": "integer",
									"minimum" : 1
								}
							}
						},
						"output": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"file": {
									"type": [
										"null", "string"
									]
								},
								"path": {
									"type": [
										"null", "string"
									]
								}
							}
						},
						"type" : {
							"enum" : [
								"data", "path", "token"
							]
						}
					}
				},
				"load": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"circular": {
							"type": "boolean"
						},
						"concurrency": {
							"type": "integer",
							"minimum" : 1
						},
						"generator" : {
							"type" : "object",
							"additionalProperties" : false,
							"properties" : {
								"addrs": {
									"type": "array",
									"items": {
										"type" : "string"
									}
								},
								"remote" : {
									"type" : "boolean"
								}
							}
						},
						"job" : {
							"type" : "object",
							"additionalProperties" : false,
							"properties" : {
								"name" : {
									"type" : [
										"null", "string"
									]
								}
							}
						},
						"limit": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"count": {
									"type": "integer",
									"minimum" : 0
								},
								"rate": {
									"type": "number",
									"minimum" : 0
								},
								"size": {
									"oneOf" : [
										{
											"type": "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : "[\\d\\.]+[KMGTPE]?B?\\-?[\\d\\.]?[KMGTPE]?B?"
										}
									]
								},
								"time": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : "[\\d]+[SsMmHhDd]?"
										}
									]
								}
							}
						},
						"metrics" : {
							"type" : "object",
							"additionalProperties" : false,
							"properties" : {
								"period" : {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : "[\\d]+[SsMmHhDd]?"
										}
									]
								},
								"precondition" : {
									"type" : "boolean"
								},
								"threshold" : {
									"type" : "number",
									"minimum" : 0,
									"maximum" : 1
								},
								"trace" : {
									"type" : "object",
									"additionalProperties" : false,
									"properties" : {
										"storageDriver" : {
											"type" : "boolean"
										},
										"storageNode" : {
											"type" : "boolean"
										},
										"itemInfo" : {
											"type" : "boolean"
										},
										"ioTypeCode" : {
											"type" : "boolean"
										},
										"statusCode" : {
											"type" : "boolean"
										},
										"reqTimeStart" : {
											"type" : "boolean"
										},
										"duration" : {
											"type" : "boolean"
										},
										"respLatency" : {
											"type" : "boolean"
										},
										"dataLatency" : {
											"type" : "boolean"
										},
										"transferSize" : {
											"type" : "boolean"
										}
									}
								}
							}
						},
						"queue" : {
							"type" : "object",
							"additionalProperties" : false,
							"properties" : {
								"size" : {
									"type" : "integer",
									"minimum" : 1
								}
							}
						},
						"type": {
							"type": "string",
							"pattern" : "[NnOoPpCcRrEeAaTtDdUuLl]+=?[\\d]?%?",
							"minLength" : 4,
							"maxLength" : 6
						}
					}
				},
				"scenario" : {
					"type" : "object",
					"additionalProperties" : false,
					"properties" : {
						"file" : {
							"type" : [
								"null", "string"
							]
						}
					}
				},
				"socket": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"bindBacklogSize": {
							"type": "integer",
							"minimum" : 0
						},
						"interestOpQueued": {
							"type": "boolean"
						},
						"keepAlive": {
							"type": "boolean"
						},
						"linger": {
							"type": "integer",
							"minimum" : 0
						},
						"rcvBuf" : {
							"oneOf" : [
								{
									"type" : "integer",
									"minimum" : 0
								},
								{
									"type" : "string",
									"pattern" : "[\\d\\.]+[KMGTPE]?B?"
								}
							]
						},
						"reuseAddr": {
							"type": "boolean"
						},
						"sndBuf" : {
							"oneOf" : [
								{
									"type" : "integer",
									"minimum" : 0
								},
								{
									"type" : "string",
									"pattern" : "[\\d\\.]+[KMGTPE]?B?"
								}
							]
						},
						"tcpNoDelay": {
							"type": "boolean"
						},
						"timeoutMilliSec": {
							"type": "integer",
							"minimum" : 0
						}
					}
				},
				"storage": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"auth": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"id": {
									"type": [
										"null", "string"
									]
								},
								"secret": {
									"type": [
										"null", "string"
									]
								},
								"token": {
									"type": [
										"null", "string"
									]
								}
							}
						},
						"driver" : {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"addrs": {
									"type": "array",
									"items": {
										"type" : "string"
									}
								},
								"port" : {
									"type" : "number",
									"minimum" : 1
								},
								"remote" : {
									"type" : "boolean"
								}
							}
						},
						"http": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"api": {
									"type": "string",
									"pattern" : "[\\w\\d]+"
								},
								"fsAccess": {
									"type": "boolean"
								},
								"headers": {
									"type": "object",
									"properties": {
									}
								},
								"namespace": {
									"type": [
										"null",
										"string"
									]
								},
								"versioning": {
									"type": "boolean"
								}
							}
						},
						"mock": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"capacity": {
									"type": "integer",
									"minimum" : 0
								},
								"container": {
									"type": "object",
									"properties": {
										"capacity": {
											"type": "integer",
											"minimum" : 0
										},
										"countLimit": {
											"type": "integer",
											"minimum" : 0
										}
									}
								},
								"fail" : {
									"type" : "object",
									"additionalProperties" : false,
									"properties" : {
										"connections" : {
											"type" : "integer",
											"minimum" : 0
										},
										"responses" : {
											"type" : "integer",
											"minimum" : 0
										}
									}
								},
								"headCount": {
									"type": "integer",
									"minimum" : 1
								},
								"node" : {
									"type" : "boolean"
								}
							}
						},
						"node" : {
							"type" : "object",
							"additionalProperties" : false,
							"properties" : {
								"addrs": {
									"type": "array",
									"items": {
										"type" : "string"
									}
								},
								"port" : {
									"type" : "number",
									"minimum" : 1
								}
							}
						},
						"ssl" : {
							"type" : "boolean"
						},
						"type": {
							"type": "string",
							"enum" : [
								"fs", "http"
							]
						}
					}
				},
				"version" : {
					"type" : "string"
				}
			}
		}
	},
	"type" : "object",
	"additionalProperties" : false,
	"properties" : {
		"blocking" : {
			"type" : "boolean"
		},
		"config" : {
			"oneOf" : [
				{
					"$ref" : "#/definitions/config"
				},
				{
					"type" : "array",
					"items" : {
						"$ref" : "#/definitions/config"
					}
				}
			]
		},
		"in" : {
			"oneOf" : [
				{
					"type" : "array"
				},
				{
					"type" : "string"
				},
				{
					"type" : "integer",
					"minimum" : 0
				}
			]
		},
		"jobs" : {
			"type" : "array",
			"items" : {
				"$ref" : "#"
			}
		},
		"type" : {
			"type" : "string",
			"enum" : [
				"command", "for", "load", "parallel", "precondition", "sequential", "mixed", "chain"
			]
		},
		"value" : {
			"oneOf" : [
				{
					"type" : "string"
				},
				{
					"type" : "integer"
				}
			]
		},
		"weights" : {
			"type" : "array",
			"items" : {
				"type" : "integer",
				"minimum" : 1
			}
		}
	},
	"required" : [
		"type"
	]
}

=== BigDataTechOnGitHub/mongoose/scenario/misc/asdjira-sltm-issue-741.json
{
	"type" : "for",
	"value" : "i",
	"in" : [
		5, 10, 15, 20, 25, 30
	],
	"jobs" : [
		{
			"type" : "load",
			"config" : {
				"item" : {
					"data" : {
						"size" : 1
					}
				},
				"storage" : {
					"http" : {
						"headers" : {
							"x-amz-meta-var-%d[0-${i}]" : "%d[0-500]"
						}
					}
				}
			}
		}
	]
}

=== BigDataTechOnGitHub/mongoose/mongoose-3.1.0/scenario/misc/rampup.json
{
	"type" : "for",
	"value" : "size",
	"in" : [
		0, "1KB", "1MB"
	],
	"config" : {
		"item" : {
			"data" : {
				"size" : "${size}"
			}
		},
		"load" : {
			"limit" : {
				"count" : 1000000,
				"time" : "10s"
			},
			"metrics" : {
				"period" : 0
			}
		}
	},
	"jobs" : [
		{
			"type" : "for",
			"value" : "threads",
			"in" : [
				1, 10, 100
			],
			"config" : {
				"item" : {
					"output" : {
						"path" : "${size}_${threads}threads"
					}
				},
				"load" : {
					"concurrency" : "${threads}"
				}
			},
			"jobs" : [
				{
					"type" : "load",
					"config" : {
						"item" : {
							"output" : {
								"file" : "${size}_${threads}threads.csv"
							}
						},
						"load" : {
							"job" : {
								"name" : "C${threads}_${size}"
							},
							"type" : "create"
						}
					}
				}, {
					"type" : "load",
					"config" : {
						"item" : {
							"input" : {
								"file" : "${size}_${threads}threads.csv"
							}
						},
						"load" : {
							"job" : {
								"name" : "R${threads}_${size}"
							},
							"type" : "read"
						}
					}
				}, {
					"type" : "load",
					"config" : {
						"item" : {
							"input" : {
								"file" : "${size}_${threads}threads.csv"
							}
						},
						"load" : {
							"job" : {
								"name" : "D${threads}_${size}"
							},
							"type" : "delete"
						}
					}
				}
			]
		}
	]
}
